cks__propics/apps/comp_poster/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^$', 'comp_poster.views.overlay', name="comp_poster-overlay"),
    url(r'^grid/$', 'comp_poster.views.grid', name="comp_poster-grid"),
)

cks__propics/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'cks__propics.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url('', include('comp_poster.urls')),
)

cks__propics/apps/comp_poster/models.py
from django.db import models

# Create your models here.

cks__propics/apps/comp_poster/forms.py
from django import forms
from comp_poster import models

class CropForm(forms.Form):
	x = forms.IntegerField(max_value=9999, required=True)
	y = forms.IntegerField(max_value=9999, required=True)
	w = forms.IntegerField(max_value=9999, required=True)
	h = forms.IntegerField(max_value=9999, required=True)
	image = forms.ImageField()

cks__propics/apps/comp_poster/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
import os
from comp_poster import forms
import urllib, cStringIO
from comp_poster.utils import general
from django.core.files.storage import default_storage as storage
from django.core.files.base import ContentFile
from PIL import Image
import datetime

def overlay(request):
	if request.method == 'POST':
		form = forms.CropForm(request.POST, request.FILES)
		if form.is_valid():
			x = form.cleaned_data.get('x')
			y = form.cleaned_data.get('y')	
			w = form.cleaned_data.get('w')
			h = form.cleaned_data.get('h')
			image = form.cleaned_data.get('image')
			image_file = cStringIO.StringIO(image.read())
			background = Image.open(image_file)

			#background = Image.open(os.path.join(os.getcwd(), 'pics', 'bg.png'))

			# sizes we have overlays for
			sizes = [200, 250, 300, 350, 400, 450, 500, 550, 600]

			size = general.round_down(w, sizes)
			#URL = 'http://4.bp.blogspot.com/-2T2XNIbAZ-s/T5-zfAjO_gI/AAAAAAAAINc/CBk42qEJPeQ/s1600/people.jpg'
			#file_from_url = cStringIO.StringIO(urllib.urlopen(URL).read())

			#background = Image.open(file_from_url).convert('RGB').crop((x, y, x+w, y+h)).resize((size,size), Image.ANTIALIAS)
			
			background = background.convert('RGB').crop((x, y, x+w, y+h)).resize((size,size), Image.ANTIALIAS)

			# Add COMP KEY part
			foreground = Image.open(storage.open('/overlays/600.png', 'r')).resize((size,size), Image.ANTIALIAS)
			background.paste(foreground, (0, 0), foreground)
			#background.save(os.path.join(os.getcwd(), 'pics', 'new.png'), "PNG")
			output = cStringIO.StringIO()
			background.save(output, "PNG")
			content = output.getvalue()
			offset = 1
			while storage.exists('/propics/%03d.png' % offset):
				offset += 1

			storage.save('/propics/%03d.png' % offset, ContentFile(content))
			output.close()
			response = HttpResponse(content, content_type='image/png')
			response['Content-Length'] = len(content)
			response['Content-Disposition'] = 'filename="cks-comp-propic.png";'
			return response
	else:
		form = forms.CropForm()

	return render(request, 'comp_poster/overlay.html', {'form': form})


def grid(request):
	files = storage.listdir('propics')[1]
	files = [_file for _file in files if _file]
	files.reverse()
	return render(request, 'comp_poster/grid.html', {'files': files})

cks__propics/apps/comp_poster/templates/comp_poster/grid.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="stylesheet" href="{% static "comp_poster/css/base.css" %}"  />

    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link rel="icon" type="image/png" href="{% static "common/img/favicon.png" %}" />

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
  <script src="{% static 'comp_poster/js/jquery.Jcrop.js' %}"></script>
  <link href="{% static 'comp_poster/css/jquery.Jcrop.min.css' %}" rel="stylesheet">
<!--
    <link href="http://netdna.bootstrapcdn.com/bootswatch/3.0.3/journal/bootstrap.min.css" rel="stylesheet">
-->
    <!--United Bootstrap
    <link href="http://netdna.bootstrapcdn.com/bootswatch/3.0.3/united/bootstrap.min.css" rel="stylesheet">
    -->


    <link href="http://netdna.bootstrapcdn.com/bootswatch/3.0.3/yeti/bootstrap.min.css" rel="stylesheet">

    <!-- uncomment for jquery-ui datetime picker widget
    <link type="text/css" href="{% static "common/css/blitzer/jquery-ui-1.10.3.custom.min.css" %}" rel="stylesheet" />
    <script src="{% static "common/js/jquery-ui-1.10.3.custom.min.js" %}" type="text/javascript"></script>
    -->

    <title>{% block title %}Comp Key Profile Pic Maker{% endblock %}</title>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->



</head>

<body>


<div class="container">
<h1>Comp Key Profile Pictures</h1>

<div class="row">
{% for file in files %}
	<a href="http://cks.s3.amazonaws.com/propics/{{ file }}"><img src="http://cks.s3.amazonaws.com/propics/{{ file }}" width="250" height="250" /></a>
	{% if forloop.counter|divisibleby:"4" %}
		</div><div class="row">
	{% endif %}
{% endfor %}
</div>

      
    </div><!-- /.container -->

  </body>
</html>

cks__propics/apps/comp_poster/templates/comp_poster/index.html
{% extends "common/base.html" %}
{% block content %}

It works!

{% endblock %}

cks__propics/apps/comp_poster/templates/comp_poster/overlay.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="stylesheet" href="{% static "comp_poster/css/base.css" %}"  />

    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
  <script src="{% static 'comp_poster/js/jquery.Jcrop.js' %}"></script>
  <link href="{% static 'comp_poster/css/jquery.Jcrop.min.css' %}" rel="stylesheet">

    <link href="http://netdna.bootstrapcdn.com/bootswatch/3.0.3/yeti/bootstrap.min.css" rel="stylesheet">


    <title>{% block title %}Comp Key Profile Pictures{% endblock %}</title>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->



<script language="javascript">

    function updateCoords(c)
    {
        jQuery('#x').val(c.x);
        jQuery('#y').val(c.y);
        jQuery('#w').val(c.w);
        jQuery('#h').val(c.h);
    };

    function bind_it()
    {
        $('form img').Jcrop({
            minSize: [200, 200],
            aspectRatio: 1.0,
            onSelect: updateCoords,
            setSelect:   [0, 0, 200, 200],
        });
    }


    $(document).ready(function() {
        $("#id_image").change(function(e) {
            $('img').remove();
            $('.jcrop-holder').remove();
            for (var i = 0; i < e.originalEvent.srcElement.files.length; i++) {
                var file = e.originalEvent.srcElement.files[i];

                var img = document.createElement("img");

                img.setAttribute("id", "crop");
                var reader = new FileReader();
                reader.onloadend = function() {
                    img.src = reader.result;
                }
                reader.readAsDataURL(file);

                $("#image_holder").html(img);
            }

            setTimeout(bind_it, 200);
        });
    });

</script>
</head>

<body>

<form name="ignore" class="hidden">
    <input type="hidden" id="page_is_back" name="page_is_back" value="0" />
</form>

<script>
    var back_bit = document.getElementById('page_is_back');
    function mark_page_back() {
        back_bit.value = '1';
    }
    if (back_bit.value == '1') {
        window.location.reload();
    }
    else
    {
        mark_page_back();
    }
</script>


<div class="container">
<h1>Make Your Comp Key Profile Picture</h1>

    <div class="row">
        <div class="col-sm-4 col-sm-offset-4">
            <img src="{% static 'common/img/sample.png' %}" style="width: 100%;" />
        </div>
    </div>


<p>
To make your Comp Key pro pic, choose a background picture, crop it (the larger selection you use, the bigger the final picture will be. Drag the corners of the selection box to use a larger area), and click submit.
</p>
{% for error in form.image.errors %}
    <div class="alert alert-danger">{{ error }}</div>
{% endfor %}
<form method="POST" enctype="multipart/form-data" class="form-container">
    {% csrf_token %}
    <input type="hidden" id="x" name="x" />
    <input type="hidden" id="y" name="y" />
    <input type="hidden" id="w" name="w" />
    <input type="hidden" id="h" name="h" />

    <div class="form-group">
        <label for="id_image">Image:</label>
        <input id="id_image" name="image" type="file" />
    </div>

    <div id="image_holder"></div>

<div class="btn-container">
    <button type="submit" class="btn btn-compkey">Submit</button>
</div>
</form>
      
    </div><!-- /.container -->


<style>
.btn-compkey
{
    border: #c0282e solid 3px;
    color: #c0282e;
    background: transparent;
    margin-bottom:20px;
}

.btn-compkey:hover, .btn-compkey:active, .btn-compkey:visited
{
    border: #c0282e solid 3px;
    background: #c0282e;
    color:white;
}
</style>
  </body>
</html>